# Generated by Django 4.0.3 on 2022-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_role',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_Role',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
