# Generated by Django 4.0.1 on 2022-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=255)),
                ('foodType', models.CharField(max_length=10)),
                ('foodPrice', models.FloatField()),
                ('foodDesc', models.TextField()),
            ],
        ),
    ]
