# Generated by Django 4.0.3 on 2022-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodImage',
            field=models.ImageField(default='NO-Image.jpg', upload_to='foodimage/'),
        ),
        migrations.AddField(
            model_name='food',
            name='foodTitle',
            field=models.CharField(default='Burger', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='foodName',
            field=models.CharField(max_length=50),
        ),
    ]
